- platform: mqtt
  name: "Master Light"
  state_topic: "smartthings/Master Light/switch"
  command_topic: "smartthings/Master Light/switch"
  brightness_state_topic: "smartthings/Master Light/level"
  brightness_command_topic: "smartthings/Master Light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true