homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_Lat
  longitude: !secret home_Long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_TZ

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

mqtt:
  broker: 192.168.2.104
  port: 11883
  client_id: home-assistant-1
  keepalive: 60

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

nest: 
  client_id: !secret nest_id
  client_secret: !secret nest_secret
# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

#group: !include groups.yaml
group: !include_dir_merge_named groups/

media_player: !include media_players.yaml

zone:
  name: Home
  latitude: !secret home_Lat
  longitude: !secret home_Long
  radius: 250
  icon: mdi:home-variant
  
zone 2:
  name: Work
  latitude: !secret work_Lat
  longitude: !secret work_Long
  radius: 250
  icon: mdi:desktop-mac

sensor: !include_dir_merge_list sensors/

switch: !include_dir_merge_list switches/
  