- platform: google_travel_time
  name: Current - Home to Work
  api_key: !secret google_maps_apikey
  origin: zone.home
  destination: zone.work
    
- platform: google_travel_time
  name: Current - Work to Home
  api_key: !secret google_maps_apikey
  origin: zone.work
  destination: zone.home